In [10]:
from rdkit import Chem
from rdkit.Chem import AllChem
import numpy as np
import os

# Read the initial molecule
mol_file_name = 'Test-structure2.mol'
mol = Chem.MolFromMolFile(mol_file_name, removeHs=False)  # Include hydrogen atoms

# Check the number of atoms in the molecule
num_atoms = mol.GetNumAtoms()
print(f"Number of atoms in the molecule: {num_atoms}")

# Define the atoms that define the bond
atom1_index = 2   # Index of the first atom defining the bond (Carbon), adjusted to start from 0
atom2_index = 64 # Ensure atom index is within range, adjusted to start from 0
stepDiff=0.5 # distance change of every step 

# Define the atoms in each fragment
fragment1_atoms = list(range(0, 50))  # Atom indices of fragment 1, adjusted to start from 0
fragment2_atoms = list(range(50, num_atoms))  # Atom indices of fragment 2

# Calculate the vector along the bond
atom1_coords = mol.GetConformer().GetAtomPosition(atom1_index)
atom2_coords = mol.GetConformer().GetAtomPosition(atom2_index)
bond_vector = np.array(atom2_coords) - np.array(atom1_coords)
bond_length = np.linalg.norm(bond_vector)
unit_bond_vector = bond_vector / bond_length

# User-provided starting distance
starting_distance = bond_length

# Extract the filename without extension
mol_filename = os.path.splitext(mol_file_name)[0]

# Loop to increase the distance along the bond
for step in range(5):
    # Calculate the distance for this step
    distance = starting_distance + stepDiff * step

    # Copy the original molecule
    new_mol = Chem.Mol(mol)

    # Calculate the translation vector along the bond
    translation_vector = unit_bond_vector * abs(distance - starting_distance)

    print(translation_vector)
    
    # Move fragment 1 along the bond
    for atom_index in fragment1_atoms:
        atom_position = new_mol.GetConformer().GetAtomPosition(atom_index)
        new_position = atom_position - translation_vector
        new_mol.GetConformer().SetAtomPosition(atom_index, new_position)

    # Save the modified molecule coordinates with the original filename as prefix
    output_file_name = f'{mol_filename}_{distance:.3f}.mol'
    Chem.MolToMolFile(new_mol, output_file_name)


Number of atoms in the molecule: 105
[ 0. -0.  0.]
[ 0.24130909 -0.16919532  0.40390948]
[ 0.48261819 -0.33839063  0.80781896]
[ 0.72392728 -0.50758595  1.21172843]
[ 0.96523638 -0.67678126  1.61563791]
